### ISSUE TITLE
I used the official demon to query the wallet address information incorrectly

### ISSUE THREAD

**Issue by qianchutao** [bnb-chain/java-sdk#125]
Exception in thread "main" com.binance.dex.api.client.BinanceDexApiException: BinanceDexApiError[code=400,message=decoding bech32 failed: checksum failed. Expected a955xp, got 07f2d2.]
	at com.binance.dex.api.client.BinanceDexApiClientGenerator.executeSync(BinanceDexApiClientGenerator.java:82)
	at com.binance.dex.api.client.impl.BinanceDexApiRestClientImpl.getAccount(BinanceDexApiRestClientImpl.java:77)
	at TestBinance.main(TestBinance.java:17)

![image](https://user-images.githubusercontent.com/72595723/147189498-00adf31d-df7d-4f4a-824a-9a5e46532368.png)

**Comment by appfile01** [comment]
Have you managed to get the sdk set up? we all have errors due to that missing ethereum jar. Could you share the file if you have it? thanks (see other open issues on the matter)

**Comment by congatobu** [comment]
@appfile01 

<repository>
            <id>jcenter</id>
            <url>https://maven.aliyun.com/repository/public</url>
</repository>

use this repository
